[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
dockerContext = "frontend"

[deploy]
startCommand = "serve -s build -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
